name: Deploy Backend to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 167.172.142.206
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/backend.TransportesJM
            git reset --hard origin/main
            git pull origin main
            npm install
            pm2 restart backend || pm2 start index.js --name backend
